name: Prod Script Workflow

on:
  push:
    paths:
      - 'data/test.csv'

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        pip install -r requirements.txt

    - name: Run production script
      run: |
        python script_prod.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "osjomete@github.com"
        git config --local user.name "oscarjmt"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Updated results after data/test.csv change" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
