name: Train Script Workflow

on:
  push:
    paths:
      - 'data/train.csv'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        pip install --no-cache-dir -r requirements.txt

    - name: Run training script
      run: |
        python script_train.py

    - name: Add changes to git
      run: |
        git config --local user.email "osjomete@gmail.com"
        git config --local user.name "occarjmt"
        git add .
        git commit -m "Updated model and results after data/train.csv change"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/oscarjmt/MLE-Ejercicio-6.git
